### ISSUE TITLE
Click `Debug in Chrome` will throw exception

### ISSUE THREAD

**Issue by jhen0409** [ptmt/react-native-desktop#46]
Xcode trace:
```
2016-03-12 03:58:49.732 TestRND[2071:11104571] *** Terminating app due to uncaught exception 'RCTNotDesignatedInitializerException', reason: 'initWithFrame: is not implemented for the class RCTTextField'
*** First throw call stack:
(
  0   CoreFoundation                      0x00007fff977a6ae2 __exceptionPreprocess + 178
  1   libobjc.A.dylib                     0x00007fff858def7e objc_exception_throw + 48
  2   TestRND                      0x00000001000d3662 -[RCTTextField initWithFrame:] + 82
  3   AppKit                              0x00007fff846b231f -[NSView init] + 62
  4   TestRND                      0x00000001000d7b57 -[RCTTextFieldManager constantsToExport] + 55
  5   TestRND                      0x0000000100073d15 __23-[RCTModuleData config]_block_invoke + 53
  6   TestRND                      0x000000010007a72d __RCTExecuteOnMainThread_block_invoke + 29
  7   libdispatch.dylib                   0x0000000100234bf9 _dispatch_client_callout + 8
  8   libdispatch.dylib                   0x000000010024b331 _dispatch_barrier_sync_f_slow_invoke + 785
  9   libdispatch.dylib                   0x0000000100234bf9 _dispatch_client_callout + 8
  10  libdispatch.dylib                   0x000000010024c6af _dispatch_main_queue_callback_4CF + 2845
  11  CoreFoundation                      0x00007fff976eccd9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
  12  CoreFoundation                      0x00007fff976a7d3d __CFRunLoopRun + 1949
  13  CoreFoundation                      0x00007fff976a7338 CFRunLoopRunSpecific + 296
  14  HIToolbox                           0x00007fff95c22935 RunCurrentEventLoopInMode + 235
  15  HIToolbox                           0x00007fff95c2276f ReceiveNextEventCommon + 432
  16  HIToolbox                           0x00007fff95c225af _BlockUntilNextEventMatchingListInModeWithFilter + 71
  17  AppKit                              0x00007fff846330ee _DPSNextEvent + 1067
  18  AppKit                              0x00007fff849ff943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
  19  AppKit                              0x00007fff84628fc8 -[NSApplication run] + 682
  20  TestRND                      0x000000010000214a main + 234
  21  libdyld.dylib                       0x00007fff8efb45ad start + 1
  22  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
rnd version: 0.4.0

**Comment by ptmt** [comment]
@jhen0409 is this empty project created from react-native-desktop init? 

Anyway, please try to `0.5.0-rc1` version from npm.

**Comment by jhen0409** [comment]
> is this empty project created from react-native-desktop init?

Yes.

I tried v0.5.0-rc1, it still has other problems:
```
2016-03-12 15:53:14.398 TestRND[15716:11259745] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArray0 longLongValue]: unrecognized selector sent to instance 0x608000000090'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff977a6ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff858def7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff977a9b9d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff976e2601 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff976e2188 _CF_forwarding_prep_0 + 120
	5   TestRND                             0x0000000100068105 -[RCTBatchedBridge handleBuffer:] + 709
	6   TestRND                             0x0000000100067dca -[RCTBatchedBridge handleBuffer:batchEnded:] + 746
	7   TestRND                             0x0000000100066b90 __60-[RCTBatchedBridge enqueueApplicationScript:url:onComplete:]_block_invoke422 + 592
	8   TestRND                             0x00000001000f2322 __58-[RCTWebSocketExecutor _executeJSCall:arguments:callback:]_block_invoke + 242
	9   TestRND                             0x00000001000f0ff4 -[RCTWebSocketExecutor webSocket:didReceiveMessage:] + 260
	10  TestRND                             0x00000001000e87f1 __33-[RCTSRWebSocket _handleMessage:]_block_invoke + 81
	11  libdispatch.dylib                   0x000000010024bfa4 _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x000000010023ebf9 _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x0000000100244046 _dispatch_queue_drain + 351
	14  libdispatch.dylib                   0x000000010024bd58 _dispatch_queue_invoke + 557
	15  libdispatch.dylib                   0x0000000100242cdf _dispatch_root_queue_drain + 1226
	16  libdispatch.dylib                   0x00000001002427d9 _dispatch_worker_thread3 + 106
	17  libsystem_pthread.dylib             0x00000001002a1458 _pthread_wqthread + 1129
	18  libsystem_pthread.dylib             0x000000010029efad start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Also, the v0.5.0-rc1 have a problem of `Cannot find module 'fast-path'`, [upstream](https://github.com/facebook/react-native/commit/fd816b1349506fb40c4229e470c0ef5c32de1e80) has been updated.

**Comment by ptmt** [comment]
Ok, thanks for a feedback, really helpful. Let's wait for 0.5.0 then, I'm almost done with the test suite, it's already fully passed on my local machine, but errored on Travis. I'm also migrating on my current project which uses 0.4.0 currently.

**Comment by ptmt** [comment]
So I'm fighting with TravisCI environment at the moment, but seems to me that 0.5.0-rc3 works fine, I've migrated the project + tried `react-native-desktop init`.

**Comment by jhen0409** [comment]
It work on v0.5.0, Thanks! :D
